// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtM97ANtwNtAtPEDgs4UOCUrMqPLf4eXQ',
    appId: '1:798779580340:web:8bb885fd692fa633c81ce1',
    messagingSenderId: '798779580340',
    projectId: 'medilink-d69f4',
    authDomain: 'medilink-d69f4.firebaseapp.com',
    storageBucket: 'medilink-d69f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUyNo1zMm7Nr9goPrTGxLm6Xdi_kbIiZk',
    appId: '1:798779580340:android:8ee1029bc6f0d812c81ce1',
    messagingSenderId: '798779580340',
    projectId: 'medilink-d69f4',
    storageBucket: 'medilink-d69f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsdM7wwBUE4g69CeJQGVBQPuC9da3QVgc',
    appId: '1:798779580340:ios:e196b960d12f0c07c81ce1',
    messagingSenderId: '798779580340',
    projectId: 'medilink-d69f4',
    storageBucket: 'medilink-d69f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsdM7wwBUE4g69CeJQGVBQPuC9da3QVgc',
    appId: '1:798779580340:ios:e196b960d12f0c07c81ce1',
    messagingSenderId: '798779580340',
    projectId: 'medilink-d69f4',
    storageBucket: 'medilink-d69f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtM97ANtwNtAtPEDgs4UOCUrMqPLf4eXQ',
    appId: '1:798779580340:web:e5f1fa2a49e92638c81ce1',
    messagingSenderId: '798779580340',
    projectId: 'medilink-d69f4',
    authDomain: 'medilink-d69f4.firebaseapp.com',
    storageBucket: 'medilink-d69f4.firebasestorage.app',
  );
}